name = "MakieHelpers"
uuid = "769ed66a-a1e3-4c16-885f-a5b16fb973c2"
authors = ["Nils Niggemann <nils.niggemann@fu-berlin.de>"]
version = "0.1.0"

[deps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
